<%-- Do not edit this file directly. See README.md --%>
<div class="row">
  <div class="col-sm-12">
    <h6>Kinome Regulation</h6>
    <div class="col-sm-12 my-3 table-responsive">
      <table class="display table table-striped table-bordered table-sm datasets">
        <thead>
          <tr>
            <th>Database</th>
            <th>Database Type</th>
            <th>Interactions</th>
            <th>Unique Kinases</th>
            <th>Unique Substrates</th>
            <th>PMID</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><span style="white-space:nowrap">ARCHS4<a href="datasets/ARCHS4/ARCHS4-2018_Mouse-Human_KINASES_unfiltered.gmt" title="ARCHS4-2018_Mouse-Human_KINASES_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>Other</td>
            <td>9936</td>
            <td>517</td>
            <td>3824</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/29636450" title="29636450" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">BIND<a href="datasets/BIND/BIND_unfiltered.gmt" title="BIND_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>PPI</td>
            <td>2533</td>
            <td>227</td>
            <td>1323</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/12519993" title="12519993" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">Harmonizome<a href="datasets/Harmonizome/Harmonizome_2018-03_Mouse_Human_KINASES_unfiltered.gmt" title="Harmonizome_2018-03_Mouse_Human_KINASES_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>Other</td>
            <td>10000</td>
            <td>79</td>
            <td>3635</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/27374120" title="27374120" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">HPRD<a href="datasets/HPRD/HPRD_2018-03_Human_KINASES_unfiltered.gmt" title="HPRD_2018-03_Human_KINASES_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>PPI</td>
            <td>5043</td>
            <td>262</td>
            <td>2159</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/18988627" title="18988627" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">huMAP<a href="datasets/huMAP/huMAP_unfiltered.gmt" title="huMAP_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>PPI</td>
            <td>1385</td>
            <td>156</td>
            <td>955</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/28596423" title="28596423" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">iPTMnet<a href="datasets/iPTMnet/iPTMnet-2018_Mouse-Human_merged_KINASES_unfiltered.gmt" title="iPTMnet-2018_Mouse-Human_merged_KINASES_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>PPI/Kinase</td>
            <td>947</td>
            <td>131</td>
            <td>724</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/29145615" title="29145615" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">iREF<a href="datasets/iREF/iREF_02-2018_Mouse-Human_merged_KINASES_unfiltered.gmt" title="iREF_02-2018_Mouse-Human_merged_KINASES_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>PPI</td>
            <td>26734</td>
            <td>329</td>
            <td>8036</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/18823568" title="18823568" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">KEGG<a href="datasets/KEGG/KEGG_unfiltered.gmt" title="KEGG_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>PPI</td>
            <td>2238</td>
            <td>131</td>
            <td>621</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/19880382" title="19880382" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">MINT<a href="datasets/MINT/MINT_2018-03_Mouse-Human-Merged_KINASES_unfiltered.gmt" title="MINT_2018-03_Mouse-Human-Merged_KINASES_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>PPI</td>
            <td>1583</td>
            <td>225</td>
            <td>1065</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/22096227" title="22096227" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a><a href="https://www.ncbi.nlm.nih.gov/pubmed/ 24234451" title=" 24234451" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">NetworkIN<a href="datasets/NetworkIN/NetworKIN_2018-03-Predictions_KINASES_unfiltered.gmt" title="NetworKIN_2018-03-Predictions_KINASES_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>PPI/Kinase</td>
            <td>5829</td>
            <td>190</td>
            <td>2006</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/17981841" title="17981841" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a><a href="https://www.ncbi.nlm.nih.gov/pubmed/ 24874572" title=" 24874572" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">Phospho.ELM<a href="datasets/Phospho.ELM/PhosphoELM_2018-03_Mouse_Human_Merged_KINASES_unfiltered.gmt" title="PhosphoELM_2018-03_Mouse_Human_Merged_KINASES_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>Kinase</td>
            <td>1441</td>
            <td>231</td>
            <td>891</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/21062810" title="21062810" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">Phosphopoint<a href="datasets/Phosphopoint/PHOSPHOPOINT_UnknownSpecies_KINASES.gmt" title="PHOSPHOPOINT_UnknownSpecies_KINASES.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>Kinase</td>
            <td>1970</td>
            <td>281</td>
            <td>1061</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/18689816" title="18689816" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">PhosphositePlus<a href="datasets/PhosphositePlus/PhosphositePlus_2018-03_Mouse_Human_KINASES_unfiltered.gmt" title="PhosphositePlus_2018-03_Mouse_Human_KINASES_unfiltered.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>Kinase</td>
            <td>6434</td>
            <td>168</td>
            <td>2680</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/22135298" title="22135298" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-sm-12">
    <h6>Protein-Protein Interaction</h6>
    <div class="col-sm-12 my-3 table-responsive">
      <table class="display table table-striped table-bordered table-sm datasets">
        <thead>
          <tr>
            <th>Database</th>
            <th>Interactions</th>
            <th>Interactors</th>
            <th>Species Included</th>
            <th>PMID</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><span style="white-space:nowrap">BIND<a href="datasets/BIND/BIND.sig" title="BIND.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>25622</td>
            <td>5528</td>
            <td>Mouse, Human, and Others</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/12519993" title="12519993" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">Biocarta<a href="datasets/Biocarta/Biocarta_X2Kweb.sig" title="Biocarta_X2Kweb.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>756</td>
            <td>352</td>
            <td>Mouse, Human, Others</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/(N/A)" title="(N/A)" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">BioGRID<a href="datasets/BioGRID/BioGRID_filtered_ppi_2018_02_26.sig" title="BioGRID_filtered_ppi_2018_02_26.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>68759</td>
            <td>7312</td>
            <td>Mouse, Human, Others (all major model organisms)</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/27980099" title="27980099" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">BioPLEX<a href="datasets/BioPLEX/BioPLEX_ppi_2017_06_07.sig" title="BioPLEX_ppi_2017_06_07.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>56553</td>
            <td>8610</td>
            <td>Human</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/26186194" title="26186194" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">DIP<a href="datasets/DIP/DIP_filtered_ppi_2017_07_12.sig" title="DIP_filtered_ppi_2017_07_12.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>3822</td>
            <td>1946</td>
            <td>Mouse, Human, Yeast, Fly, C.elegans, H.pylori, Rat</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/11752321" title="11752321" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">figeys<a href="datasets/figeys/figeys.sig" title="figeys.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>6452</td>
            <td>2033</td>
            <td>Human</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/17353931" title="17353931" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">HPRD<a href="datasets/HPRD/HPRD.sig" title="HPRD.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>47496</td>
            <td>7490</td>
            <td>Human</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/18988627" title="18988627" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">huMAP<a href="datasets/huMAP/huMAP_X2Kweb.sig" title="huMAP_X2Kweb.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>62214</td>
            <td>6061</td>
            <td>Human</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/28596423" title="28596423" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">InnateDB<a href="datasets/InnateDB/innateDB_filtered_ppi_2017_07_12.sig" title="innateDB_filtered_ppi_2017_07_12.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>4576</td>
            <td>1523</td>
            <td>Mouse, Human, Bovine</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/23180781" title="23180781" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">IntAct<a href="datasets/IntAct/IntAct_filtered_ppi_2017_07_13.sig" title="IntAct_filtered_ppi_2017_07_13.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>15726</td>
            <td>4186</td>
            <td>Mouse, Human, and Others</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/24234451" title="24234451" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a><a href="https://www.ncbi.nlm.nih.gov/pubmed/ 22121220" title=" 22121220" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">iREF<a href="datasets/iREF/iREF_02-2018_Mouse-Human_KINASES_PPI.sig" title="iREF_02-2018_Mouse-Human_KINASES_PPI.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>28417</td>
            <td>5403</td>
            <td>Mouse, Human</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/18823568" title="18823568" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">KEGG<a href="datasets/KEGG/KEGG_X2Kweb.sig" title="KEGG_X2Kweb.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>13993</td>
            <td>1198</td>
            <td>Mouse, Human, and Others</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/19880382" title="19880382" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">MINT<a href="datasets/MINT/MINT-03-2018_Mouse-Human_PPI.sig" title="MINT-03-2018_Mouse-Human_PPI.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>75065</td>
            <td>9415</td>
            <td>Mouse, Human, and Others</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/22096227" title="22096227" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a><a href="https://www.ncbi.nlm.nih.gov/pubmed/ 24234451" title=" 24234451" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">MiPS<a href="datasets/MiPS/MIPS.sig" title="MIPS.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>606</td>
            <td>373</td>
            <td>Mouse, Human, and Others</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/9399795" title="9399795" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a><a href="https://www.ncbi.nlm.nih.gov/pubmed/ 15531608" title=" 15531608" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">PDZbase<a href="datasets/PDZbase/pdzbase.sig" title="pdzbase.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>244</td>
            <td>159</td>
            <td>Mouse, Human, and Others</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/15513994" title="15513994" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">PPID<a href="datasets/PPID/ppid_X2Kweb.sig" title="ppid_X2Kweb.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>6998</td>
            <td>1208</td>
            <td>Mouse, Human, Rat, and Others</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/14755292" title="14755292" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">Sets2Networks<a href="datasets/Sets2Networks/predictedPPI.sig" title="predictedPPI.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>3000</td>
            <td>828</td>
            <td>Mouse, Human, and Others</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/22824380" title="22824380" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">SNAVI<a href="datasets/SNAVI/SNAVI_X2Kweb.sig" title="SNAVI_X2Kweb.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>2007</td>
            <td>442</td>
            <td>Mouse, Human, and Others</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/19154595" title="19154595" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">Stelzl<a href="datasets/Stelzl/Stelzl.sig" title="Stelzl.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>6207</td>
            <td>1702</td>
            <td>Human</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/16169070" title="16169070" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">Vidal<a href="datasets/Vidal/vidal.sig" title="vidal.sig" style="padding-left:5px"><img src="http://satie.bioinfo.cnio.es/themes/fustero/images/icon_6.png" width="15"/></a></span></td>
            <td>6726</td>
            <td>2541</td>
            <td>Human</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/16189514" title="16189514" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="col-sm-12">
    <h6>Transcriptional Regulation</h6>
    <div class="col-sm-12 my-3 table-responsive">
      <table class="display table table-striped table-bordered table-sm datasets">
        <thead>
          <tr>
            <th>Database</th>
            <th>Interactions [Mouse]</th>
            <th>Unique TFs [Mouse]</th>
            <th>Unique Interactors [Mouse]</th>
            <th>Interactions [Human]</th>
            <th>Unique TFs [Human]</th>
            <th>Unique Interactors [Human]</th>
            <th>PMID</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><span style="white-space:nowrap">ARCHS4<a href="datasets/ARCHS4/ARCHS4_Mouse_transcription_factor_gene_set_2018_02.gmt" title="ARCHS4_Mouse_transcription_factor_gene_set_2018_02.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a><a href="datasets/ARCHS4/ARCHS4-08-2017_Human_transcription-factor-gene-set.gmt" title="ARCHS4-08-2017_Human_transcription-factor-gene-set.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>518466</td>
            <td>1734</td>
            <td>21857</td>
            <td>472585</td>
            <td>1724</td>
            <td>21918</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/29636450" title="29636450" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">ChEA_2016<a href="datasets/ChEA_2016/CHEA-2016_Human_TF.gmt" title="CHEA-2016_Human_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a><a href="datasets/ChEA_2016/CHEA-2016_Mouse_TF.gmt" title="CHEA-2016_Mouse_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>535545</td>
            <td>194</td>
            <td>34462</td>
            <td>461570</td>
            <td>178</td>
            <td>35204</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/20709693" title="20709693" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">CREEDS<a href="datasets/CREEDS/CREEDS-manual-single-gene-perturbations-from-GEO_Human_TF.txt" title="CREEDS-manual-single-gene-perturbations-from-GEO_Human_TF.txt" style="padding-left:5px"><img width="15"/></a><a href="datasets/CREEDS/CREEDS-manual-single-gene-perturbations-from-GEO_Mouse_TF.txt" title="CREEDS-manual-single-gene-perturbations-from-GEO_Mouse_TF.txt" style="padding-left:5px"><img width="15"/></a></span></td>
            <td>6140050</td>
            <td>265</td>
            <td>23170</td>
            <td>3583008</td>
            <td>174</td>
            <td>20592</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/27667448" title="27667448" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">ENCODE_2015<a href="datasets/ENCODE_2015/ENCODE-2015_Human_TF.gmt" title="ENCODE-2015_Human_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a><a href="datasets/ENCODE_2015/ENCODE-2015_Mouse_TF.gmt" title="ENCODE-2015_Mouse_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>259695</td>
            <td>44</td>
            <td>18170</td>
            <td>1218728</td>
            <td>175</td>
            <td>22008</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/22955616" title="22955616" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">Enrichr_Submissions-Cooccurence<a href="datasets/Enrichr_Submissions-Cooccurence/Enrichr-Submissions-TF-Gene-Cooccurence-2018_UnknownSpecies_TF.gmt" title="Enrichr-Submissions-TF-Gene-Cooccurence-2018_UnknownSpecies_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>516300</td>
            <td>1721</td>
            <td>12487</td>
            <td>516300</td>
            <td>1721</td>
            <td>12487</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/23586463" title="23586463" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">huMAP<a href="datasets/huMAP/huMAP_07-2017_Human_TF.gmt" title="huMAP_07-2017_Human_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>NA</td>
            <td>NA</td>
            <td>NA</td>
            <td>14017</td>
            <td>419</td>
            <td>2109</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/28596423" title="28596423" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">iREF<a href="datasets/iREF/iREF_02-2018_Human_TF.gmt" title="iREF_02-2018_Human_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a><a href="datasets/iREF/iREF_02-2018_Mouse_TF.gmt" title="iREF_02-2018_Mouse_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>7239</td>
            <td>402</td>
            <td>3454</td>
            <td>57042</td>
            <td>1372</td>
            <td>11021</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/18823568" title="18823568" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">JASPAR-TRANSFAC<a href="datasets/JASPAR-TRANSFAC/JASPAR-TRANSFAC_Human.gmt" title="JASPAR-TRANSFAC_Human.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a><a href="datasets/JASPAR-TRANSFAC/JASPAR-TRANSFAC_Mouse.gmt" title="JASPAR-TRANSFAC_Mouse.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>139520</td>
            <td>104</td>
            <td>20895</td>
            <td>424314</td>
            <td>222</td>
            <td>22258</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/14681366" title="14681366" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a><a href="https://www.ncbi.nlm.nih.gov/pubmed/ 20438625" title=" 20438625" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">TF-PPIs_Genes2Fans<a href="datasets/TF-PPIs_Genes2Fans/TF-PPIs-GENES2FANS-2012_UnknownSpecies_TF.gmt" title="TF-PPIs-GENES2FANS-2012_UnknownSpecies_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>22525</td>
            <td>278</td>
            <td>6001</td>
            <td>22525</td>
            <td>278</td>
            <td>6001</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/22748121" title="22748121" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
          <tr>
            <td><span style="white-space:nowrap">TF-LOF_Expression_GEO<a href="datasets/TF-LOF_Expression_GEO/TF-LOF-Expression-GEO_07-2017_Human_TF.gmt" title="TF-LOF-Expression-GEO_07-2017_Human_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a><a href="datasets/TF-LOF_Expression_GEO/TF-LOF-Expression-GEO_07-2017_Mouse_TF.gmt" title="TF-LOF-Expression-GEO_07-2017_Mouse_TF.gmt" style="padding-left:5px"><img src="https://s3.amazonaws.com/go-public/image/go-logo-icon.png" width="15"/></a></span></td>
            <td>86951</td>
            <td>82</td>
            <td>23876</td>
            <td>85829</td>
            <td>43</td>
            <td>23585</td>
            <td><span style="white-space:nowrap"><a href="https://www.ncbi.nlm.nih.gov/pubmed/(unpublished)" title="(unpublished)" style="padding-left:5px"><img src="http://www.ics-mci.fr/static/img/pubmed-icon.png" width="25"/></a></span></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>