package edu.mssm.pharm.maayanlab.X2K;

import org.junit.Test;
import org.mockito.Mockito;

import java.util.ArrayList;
import java.util.Arrays;

public class AppTest extends Mockito{
	
	@Test
	public void testPostRequest() {

//		TESTS TEMPORARILY REMOVED
//		HttpServletRequest request = mock(HttpServletRequest.class);
//        HttpServletResponse response = mock(HttpServletResponse.class);
//
//        ServletContextEvent event = mock(ServletContextEvent.class);
//        Context context = new Context();
//        context.contextInitialized(event);
//
//        ArrayList<String> inputList = getInputList();
//
//        StringWriter output = new StringWriter();
//        PrintWriter writer = new PrintWriter(output);
//
//        try {
//        	when(request.getSession()).thenReturn(mock(HttpSession.class));
//			when(response.getWriter()).thenReturn(writer);
//			when(request.getParameter(ChEA.SORT_BY)).thenReturn(ChEA.PVALUE);
//
//			X2KServlet.enrichList(inputList, request, response);
//		} catch (IOException e) {
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		} catch (ServletException e) {
//			e.printStackTrace();
//		}
//
//        writer.flush();
//        verify(request, times(2)).getParameter(ChEA.SORT_BY);
//        assertTrue(output.toString().contains("network"));
//        assertTrue(output.toString().contains("nodes"));

        System.out.println("TESTS PASSED");
//        System.out.println(output.toString());
		
	}

	private ArrayList<String> getInputList() {
		String[] inputArray = {"PRPF8",
				"NDUFB11",
				"BRK1",
				"VDAC2",
				"MSRB1",
				"NHP2",
				"APMAP",
				"FNTA",
				"LSM4",
				"NDUFB2",
				"CLTA",
				"POMP",
				"MRPL43",
				"PSMD6",
				"ZNHIT6",
				"SRP68",
				"SAT1",
				"ICT1",
				"TM2D3",
				"TIMM13",
				"SUMO3",
				"MRPS18A",
				"RAB28",
				"TXN",
				"RALGAPB",
				"PSMA6",
				"LCMT1",
				"PRNP",
				"TCP1",
				"SLC25A5",
				"UPP1",
				"HSPD1",
				"SLC7A6OS",
				"COPG1",
				"C12orf57",
				"NGRN",
				"NKAP",
				"SCCPDH",
				"COX7A2",
				"MRPL19",
				"CTSS",
				"UBE2L3",
				"NCKAP1",
				"HERPUD2",
				"DHPS",
				"VPS28",
				"SDF2",
				"SLC43A2",
				"STRAP",
				"PDE9A",
				"MRPL41",
				"TOMM6",
				"POMGNT1",
				"ATG4B",
				"PSMA7",
				"SWI5",
				"PHAX",
				"PHF23",
				"SCAF4",
				"AIMP1",
				"FIBP",
				"CLPP",
				"ATP5D",
				"DCTN3",
				"CITED2",
				"PPAN",
				"DDX1",
				"UBXN6",
				"PSMF1",
				"NDUFA7",
				"ACOT9",
				"NEDD8",
				"NAA20",
				"HN1",
				"RAN",
				"UBA2",
				"ATP5G3",
				"HMGCS2",
				"TNPO3",
				"CD81",
				"GRPEL1",
				"MALSU1",
				"ATP5J2",
				"PSMB3",
				"TXNDC16",
				"UTP3",
				"FTH1",
				"SURF2",
				"DDX47",
				"HEPH",
				"ASNS",
				"ELOF1",
				"DNAJC8",
				"UQCRB",
				"PPIA",
				"DHX38",
				"STOML2",
				"DHTKD1",
				"GABPB1",
				"ZGPAT",
				"HIGD1B",
				"COX18",
				"HSPA8",
				"BAX",
				"HYPK",
				"TCEB1",
				"MRPL28",
				"SPATS2L",
				"VPS11",
				"PIAS2",
				"COMMD3",
				"INO80C",
				"VPS45",
				"TBCE",
				"DDX23",
				"PSMB6",
				"TMEM184C",
				"ND1",
				"GPANK1",
				"CLPX",
				"FKBP3",
				"GTF2F1",
				"SSX2IP",
				"FAM104A",
				"ABHD10",
				"HSPE1",
				"ACSL5",
				"COX4I1",
				"COX7B",
				"ATP6V0D1",
				"PSMA4",
				"RANBP3",
				"MRPS24",
				"GATAD2A",
				"ATP5A1",
				"ABCG1",
				"RGS10",
				"PRMT1",
				"NDUFV3",
				"PSMC2",
				"PRDX5",
				"PSMA5",
				"MYEOV2",
				"CTPS2",
				"MLYCD",
				"SUMO1",
				"OGFR",
				"AIMP2",
				"ACBD6",
				"ANKS1B",
				"WDR26",
				"GNL3",
				"TMEM128",
				"SF3B1",
				"TYW3",
				"TBK1",
				"CISD1",
				"SCNM1",
				"PIGS",
				"MCRS1",
				"PSMC6",
				"PDCD5",
				"FAHD2B",
				"TIMM9",
				"COQ4",
				"RRP15",
				"TRAP1",
				"TMEM80",
				"PSMD2",
				"IMPA2",
				"KLF11",
				"SLC25A3",
				"CIB2",
				"SPRYD7",
				"NDUFS8",
				"RAB24",
				"MAST4",
				"EIF6",
				"ARMCX2",
				"HIGD2A",
				"FIS1",
				"ARL6",
				"MRFAP1",
				"JTB",
				"AKR1A1",
				"SLCO1C1",
				"SCO1",
				"ACD",
				"UQCRQ",
				"SUCLG1",
				"TRMT6",
				"VWA8",
				"TMEM5",
				"PAFAH1B2",
				"CASC4",
				"DDRGK1",
				"RNMT",
				"LY6E",
				"YWHAE",
				"LAMTOR5",
				"MYBBP1A",
				"RARS",
				"SLC35B4",
				"UBA6",
				"ATP5B",
				"DLD",
				"ZDHHC7",
				"SFSWAP",
				"MRPS35",
				"PITRM1",
				"UGDH",
				"TRMT112",
				"UBE2V2",
				"ABCF1",
				"ZRSR2",
				"ASCC1",
				"TMEM138",
				"FAM175B",
				"LONP2",
				"PNPLA7",
				"MCFD2",
				"BAG1",
				"MB21D2",
				"R3HDM1",
				"SAP30L",
				"RABAC1",
				"EXOSC5",
				"MAD2L1BP",
				"HADHB",
				"PARK7",
				"ANAPC7",
				"NAA10",
				"JMJD6",
				"GRWD1",
				"IPO4",
				"MRPL1",
				"MRPL35",
				"DOLK",
				"FAM118A",
				"NAPA",
				"ARID1B",
				"RPF2",
				"CPSF7",
				"GLRX2",
				"USPL1",
				"CNOT10",
				"GRIK4",
				"NDUFC1",
				"TMEM65",
				"CHCHD10",
				"MRPL33",
				"WBSCR22",
				"TBL3",
				"STK24",
				"TXNDC12",
				"NDUFA2",
				"STX7",
				"ANAPC5",
				"PSMD13",
				"MRPL21",
				"FLII",
				"EEF1D",
				"BBC3",
				"SSNA1",
				"GALK2",
				"BCAP31",
				"BUD13",
				"ST8SIA3",
				"EIF2B4",
				"PLEKHA3",
				"PPCS",
				"MRPS28",
				"DGAT1",
				"STMN1",
				"PTRH1",
				"ICMT",
				"SLC30A4",
				"SEPHS2",
				"ACP1",
				"PSMD7",
				"MINPP1",
				"MIF",
				"COG1",
				"VPS51",
				"SMPD1",
				"ADCK5",
				"PDSS2",
				"RNF146",
				"DDIT3",
				"OTUD7B",
				"MRPL54",
				"ERCC3",
				"STUB1",
				"CMSS1",
				"CSNK2B",
				"VDAC3",
				"BRD9",
				"FANCE",
				"COX2",
				"TBRG4"};
		ArrayList<String> inputList = new ArrayList<String>(Arrays.asList(inputArray));
		return inputList;
	}
}